# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-nanoseq-1.1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.8.6
  - conda-forge::markdown=3.3.3
  - conda-forge::pymdown-extensions=8.0.1
  - conda-forge::pygments=2.7.2
  - conda-forge::pigz=2.3.4
  - conda-forge::seaborn=0.10.1
  - conda-forge::r-base=4.0.3
  
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.9
  - bioconda::qcat=1.1.0
  - bioconda::pycoqc=2.5.0.3
  - bioconda::nanoplot=1.32.1
  - bioconda::samtools=1.11
  - bioconda::minimap2=2.17
  - bioconda::graphmap=0.6.3
  - bioconda::bedtools=2.29.2
  - bioconda::ucsc-bedgraphtobigwig=377
  - bioconda::ucsc-bedtobigbed=377
  - bioconda::stringtie=2.1.4
  - bioconda::subread=2.0.1
  - bioconda::bioconductor-deseq2=1.28.0
  - bioconda::bioconductor-drimseq=1.16.0
  - bioconda::bioconductor-dexseq=1.34.0
  - bioconda::bioconductor-stager=1.10.0
  - bioconda::bioconductor-bsgenome=1.56.0
