name: nf-core CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['19.10.0', '']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      #- name: Pull image (Cant pull standard single image for this pipeline as we are using individual BioContainers)
      #  run: |
      #    docker pull nfcore/nanoseq:dev && docker tag nfcore/nanoseq:dev nfcore/nanoseq:dev
      - name: Default test
        run: |
          nextflow run ${GITHUB_WORKSPACE} -ansi-log false -profile test,docker
      - name: Graphmap2 alignment
        run: |
          nextflow run ${GITHUB_WORKSPACE} -ansi-log false -profile test,docker --aligner graphmap2
      - name: Non-barcoded test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -ansi-log false -profile test_nonbc,docker
      - name: Skip alignment
        run: |
          nextflow run ${GITHUB_WORKSPACE} -ansi-log false -profile test_nonbc,docker --skip_alignment
      - name: Skip QC
        run: |
          nextflow run ${GITHUB_WORKSPACE} -ansi-log false -profile test_nonbc,docker --skip_alignment --skip_qc
